name: gittodocker

on: push

job:
    validation:

    name: docker to git
    runs-on: ubuntu-latest

    name: checkoutmyfile
    uses: actions/checkout@v3

    # name: Setpup python
    # uses: actions/setup-python@v4

    # name: Dependencies
    # run:  pip install pandas numpy

    name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: sahil2705/gittodocker:gitnew



